import "../../styles/main.scss";
import SideMenu from "../../components/app-layouts/SideMenu";
import Navbar from "../../components/app-layouts/TopNavbar";

export const metadata = {
  title: "DMC hrm",
  description: "Generated by Mamun",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="wrapper">
          <div className="side_nav">
            <SideMenu />
          </div>
          <div className="content shadow float-end">
            <div>
              <Navbar />
            </div>
            <div className="m-3 p-3 bg-white rounded">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
