import "bootstrap/dist/css/bootstrap.min.css";
import "../styles/globals.scss";
import SideMenu from "../components/app-layouts/SideMenu";
import Navbar from "../components/app-layouts/TopNavbar";

export const metadata = {
  title: "DMC HRM",
  // description: "Generated by Mamun",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
